discrete_values:
  hatch: [20]
  starting_pos: ["LL", "LR", "UL", "UR"]
  heading: ["x", "y"]
  exp_factor: [0.1]

range:
  v_scan:
    start: 0.2
    stop: 0.8
    step: 0.2

  melt_tail_length:
    start: 60
    stop: 71
    step: 5

  melt_depth:
    start: 30
    stop: 36
    step: 5

  cap_height:
    start: 7
    stop: 12
    step: 2

  spot_width:
    base: hatch
    start: -10
    stop: 6
    step: 2

  HAZ_width:
    base: hatch
    start: 20
    stop: 31
    step: 2

offset:
  HAZ_tail:
    base: melt_tail_length
    offset: 15

  depth_HAZ:
    base: melt_depth
    offset: 5

  cap_HAZ:
    base: cap_height
    offset: 5


